name: OnePage

on: 
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install & Run Apache2
        run: | 
		  sudo apt update
		  sudo apt -y install apache2
		  sudo systemctl enable apache2
		  sudo systemctl restart apache2

      - name: Run a script
        run: |
          ls la
          echo Congratulations! Everything OK!

